name: Liquibase DEV1 Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'database/liquibase/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Liquibase
        run: liquibase --version

      - name: Install PostgreSQL driver
        run: liquibase lpm add postgresql --global --skip-existing

      - name: Deploy database
        working-directory: database/liquibase
        env:
          LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.DEV1_DB_PASSWORD }}
        run: liquibase update